const { supabaseUrl, supabaseKey, adminEmail } = window.QUIZ_CONFIG;
const db = window.supabase.createClient(supabaseUrl, supabaseKey);
const root = document.querySelector('#admin');
const baseUrl = new URL('.', location.href).href;
const stationSlugs = ['stanoviste-1', 'stanoviste-2', 'stanoviste-3', 'stanoviste-4'];
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value ?? ''; return el.innerHTML; }
async function rpc(name, args = {}) { const { data, error } = await db.rpc(name, args); if (error) throw error; return data; }
function login() { root.innerHTML = `<p class="lead">Jen pro správce kvízu. Pošleme vám přihlašovací odkaz e‑mailem.</p><form id="login"><label>E‑mail<input value="${escapeHtml(adminEmail)}" type="email" required></label><button class="primary">Poslat přihlašovací odkaz</button></form><p id="message"></p>`; document.querySelector('#login').addEventListener('submit', async event => { event.preventDefault(); const email = event.currentTarget.querySelector('input').value; const message = document.querySelector('#message'); const { error } = await db.auth.signInWithOtp({ email, options: { emailRedirectTo: new URL('admin.html', baseUrl).href } }); message.className = error ? 'error' : 'success'; message.textContent = error ? error.message : 'Odkaz je odeslaný. Otevřete ho ve stejném prohlížeči.'; }); }
async function renderAdmin() { const { data: { session } } = await db.auth.getSession(); if (!session || session.user.email?.toLowerCase() !== adminEmail) { login(); return; }
  root.innerHTML = `<div class="admin-grid"><section><h2>Přidat hráče</h2><form id="add-player"><label>Přezdívka<input name="nickname" required maxlength="40" placeholder="např. Sněhulák 7"></label><button class="primary">Vytvořit osobní adresu</button></form><p id="result"></p><h2>Stanoviště</h2><div class="station-links">${stationSlugs.map((slug, i) => `<a href="${baseUrl}index.html?station=${slug}" target="_blank">Stanoviště ${i + 1}: ${baseUrl}index.html?station=${slug}</a>`).join('')}</div><p class="muted">Tyto čtyři adresy proměníte v QR kódy pro stanoviště.</p></section><section><h2>Hráči a jejich osobní adresy</h2><div id="players" class="player-list"><p class="muted">Načítám…</p></div></section></div>`;
  document.querySelector('#add-player').addEventListener('submit', createPlayer); await loadPlayers(); }
async function createPlayer(event) { event.preventDefault(); const form = event.currentTarget; const nickname = new FormData(form).get('nickname').trim(); const result = document.querySelector('#result'); const button = form.querySelector('button'); button.disabled = true; try { const data = await rpc('admin_create_participant', { p_nickname: nickname }); const player = data[0]; const url = `${baseUrl}index.html?player=${player.qr_token}`; result.className = 'success'; result.innerHTML = `Hotovo: <code>${escapeHtml(url)}</code>`; form.reset(); await loadPlayers(); } catch (error) { result.className = 'error'; result.textContent = error.message; } finally { button.disabled = false; } }
async function loadPlayers() { const holder = document.querySelector('#players'); try { const players = await rpc('admin_list_participants'); holder.innerHTML = players.length ? players.map(player => { const url = `${baseUrl}index.html?player=${player.qr_token}`; return `<article class="player"><strong>${escapeHtml(player.nickname)}</strong><span class="muted">${player.points} bodů · ${player.answered} odpovědí</span><code>${escapeHtml(url)}</code><button class="copy" data-copy="${escapeHtml(url)}">Kopírovat adresu</button></article>`; }).join('') : '<p class="muted">Zatím žádní hráči.</p>'; holder.querySelectorAll('[data-copy]').forEach(button => button.addEventListener('click', async () => { await navigator.clipboard.writeText(button.dataset.copy); button.textContent = 'Zkopírováno'; setTimeout(() => button.textContent = 'Kopírovat adresu', 1400); })); } catch (error) { holder.innerHTML = `<p class="error">${escapeHtml(error.message)}</p>`; } }
db.auth.onAuthStateChange(() => renderAdmin());
renderAdmin();
